#!/bin/bash

mkdir results/cifar_mwu_train_with_decay2
nohup python ./cifar_mwu_train.py --train_dir=./results/cifar10_mwu_train_with_decay2 --print_steps=10 --batch_size=128 --learning_rate=0.1 > results/cifar_mwu_train_with_decay2/log.txt 2>&1 &
