#!/bin/bash

mkdir results/cifar10_train_with_decay
nohup python ./cifar_train.py --train_dir=./results/cifar10_train_with_decay --print_steps=10 --batch_size=32 --learning_rate=0.0001 > results/cifar10_train_with_decay/log.txt 2>&1 &
