#!/bin/bash

mkdir results/mnist_adv_mwu_ep0.3_u20_50
nohup python ./mnist_adv_mwu_train.py --train_dir=results/mnist_adv_mwu_ep0.3_u20_50 --learning_rate=0.1 --u=20 --u2=50 > results/mnist_adv_mwu_ep0.3_u20_50/log.txt 2>&1 &